const goodButton = new ButtonElement('good')
const badButton = new ButtonElement('bad')
const goodSpan = new SpanElement('good')
const badSpan = new SpanElement('bad')
const loadedData = new LocaleStorage()
const moodObj = new Mood()
const emoji = new Emoji()
moodObj.loadFromLocaleStorage()
goodSpan.setHtmlContent(String(moodObj.good))
badSpan.setHtmlContent(String(moodObj.bad))
goodButton.getClick()
badButton.getClick()
